#  KEYBINDS  this is where everthing begins so lets do this pownkumar(founder of korelium) with the heart full of live with RAMYA

#terminal
bind = $mainmod, RETURN , exec , $terminal 

# launcher 

bind = $mainmod, D , exec , $menu 

# file manager 

bind = $mainmod, E , exec , $fileManager 

#close the windows 

bind = $mainmod, Q , killactive 

# move focused 

bind = $mainmod, H , movefocus, l
bind = $mainmod, L , movefocus, r 
bind = $mainmod, K , movefocus, u
bind = $mainmod, J , movefocus, d

# move windows as we see fit 

bind = $mainmod SHIFT, H , movewindow, l
bind = $mainmod SHIFT, L , movewindow, r
bind = $mainmod SHIFT, K , movewindow, u
bind = $mainmod SHIFT, J , movewindow, d

# full screen 

bind = $mainmod , F , fullscreen 
bind = $mainmod , SPACE , togglefloating

# restart

bind = $mainmod SHIFT , R , exec , hyprctl reload 

# exit

bind = $mainmod SHIFT , Q , exit


#################################################  switch workspace #######################################


bind = $mainmod, 1 , workspace, 1
bind = $mainmod, 2 , workspace, 2
bind = $mainmod, 3 , workspace, 3
bind = $mainmod, 4 , workspace, 4
bind = $mainmod, 5 , workspace, 5
bind = $mainmod, 6 , workspace, 6
bind = $mainmod, 7 , workspace, 7
bind = $mainmod, 8 , workspace, 8
bind = $mainmod, 9 , workspace, 9

############################################### move window to workspace ###################################

bind = $mainmod SHIFT , 1 , movetoworkspace , 1 
bind = $mainmod SHIFT , 2 , movetoworkspace , 2 
bind = $mainmod SHIFT , 3 , movetoworkspace , 3 
bind = $mainmod SHIFT , 4 , movetoworkspace , 4 
bind = $mainmod SHIFT , 5 , movetoworkspace , 5 
bind = $mainmod SHIFT , 6 , movetoworkspace , 6 
bind = $mainmod SHIFT , 7 , movetoworkspace , 7 
bind = $mainmod SHIFT , 8 , movetoworkspace , 8 
bind = $mainmod SHIFT , 9 , movetoworkspace , 9 


##############################################  move to the workspace with mouse scroll #####################

bind = $mainmod , mouse_down , workspace, e+1
bind = $mainmod , mouse_up, workspace , e-1


